config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'pages#home'

  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }, unless: proc { |a| a.password.blank? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  before_action :logged_in_user

  include SessionsHelper

  def admin_only
    return true if current_user.admin?
    flash[:alert] = 'You are not authorised to do that.'
    redirect_to root_path
  end

  # TODO: spec for this
  def logged_in_user
    return if logged_in?
    store_location
    redirect_to sessions_new_path, alert: 'Please log in.'
  end

  # TODO: spec for this
  def redirect_back_or(location)
    redirect_to(session[:return_to] || location)
    session.delete(:return_to)
  end

  # TODO: spec for this
  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :logged_in_user, only: [:home]

  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :logged_in_user, only: [:new, :create, :destroy]

  def new
  end

  def create
    user = User.find_by(email: params[:sessions][:email])
    if user && user.authenticate(params[:sessions][:password])
      reset_session
      sign_in(user)
      redirect_back_or root_path
    else
      flash.now[:action] = 'Invalid username/password combination'
      render :new
    end
  end

  def destroy
    sign_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,    only: [:show, :edit, :update, :destroy]
  before_action :admin_only,  only: [:destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if current_user == @user
      redirect_to(current_user, alert: 'You cannot delete yourself.')
    else
      @user.destroy
      redirect_to users_url, alert: 'User was successfully destroyed.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find_by(id: params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    return unless session[:current_user_id]
    @current_user ||= User.find(session[:current_user_id])
  end

  def logged_in?
    session[:current_user_id].present?
  end

  def sign_in(user)
    session[:current_user_id] = user.id
  end

  def sign_out
    session[:current_user_id] = nil
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Startup</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to 'Home', root_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if logged_in? %>
                <a class=navbar-brand><%= current_user.name %></a>

                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to 'Profile', user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li><%= link_to 'Log out', sessions_path, method: :delete %></li>
                  </ul>
                </li>



              <% else %>
                <li><%= link_to 'Log in', sessions_new_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <% if flash[:notice] %> <div class='alert alert-success'><%= flash[:notice] %></div> <% end %>
      <% if flash[:alert] %>   <div class='alert alert-danger'><%= flash[:alert] %></div>  <% end %>

      <%= yield %>

    </div> <!-- /container -->
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to the startup app</h1>

app/views/users/_form.html.erb
<%= simple_form_for(@user, html: {class: 'form form-horizontal'} ) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :confirmation %><br>
    <%= f.password_field :confirmation %>
  </div>
  <div class="field">
    <%= f.check_box :admin %> <%= f.label :admin %>
  </div>
  <div class="actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class='col-lg-6 col-lg-offset-3'>
  <h1>User Account</h1>
  <%= render 'form' %>

  <%= link_to 'Show', @user %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<%= link_to 'New User', new_user_path,  class: 'pull-right btn btn-primary'%>
<table class='table table-condensed table-striped table-hover'>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="2"></th>
    </tr>

    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Edit', edit_user_path(user), id: "edit_#{user.id}" %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, id: "delete_#{user.id}" %></td>
      </tr>
    <% end %>
</table>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="col-lg-6 col-lg-offset-3">
  <%= render 'form' %>
  <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div class='col-lg-6 col-lg-offset-3'>
<table class='table table-condensed table-striped'>
  <tr>
    <th>Name:</th>
    <td><%= @user.name %></td>
  </tr>

  <tr>
    <th>Email:</th>
    <td><%= @user.email %></td>
  </tr>

  <tr>
    <th>Admin:</th>
    <td><span class='glyphicon glyphicon-<%= @user.admin ? 'ok-circle' : 'remove-circle' %>'</td>
  </tr>
</table>

<%= link_to 'Edit', edit_user_path(@user), html: {class: 'btn btn-primary'} %>
</div>